pipeline {
  agent any
  stages {
    stage("Cleanup Workspace") {
     
      steps {
        deleteDir()
      }
    }
    stage("Checkout TestAutomation Project") {
      steps {
      	echo 'deploying the version: ${params.VERSION}'
        git branch: 'master',
        url: 'https://github.com/prateeksethiDev/Test_UI_API_Repo.git',
        credentialsId: 'GitDevAccount'
      }
    }
    stage("Spin up the Selenium Grid") {
      steps {
      	echo 'Spining up the Selenium Grid'
         sh label: '',script: 'docker-compose -f TestAutomation_UI_API/docker-compose-v3.yml up --scale chrome=3'
      }
    }
    stage("Build and run tests") {
      steps {
        echo 'Running Test Automation'
    	sh label: 'Running pom.xml', script: 'mvn -f TestAutomation_UI_API/pom.xml clean test'
      }
    }  
  }
  //The post step as sending email that executed always 
  post{    
      always{
      steps {
        sh label: '',script: 'docker-compose -f TestAutomation_UI_API/docker-compose-v3.yml down'
      }
      
             emailext attachLog: true, body: '''Hello Admin,

Please find the the attached test execution report for project: $PROJECT_NAME - BUILD# - $BUILD_NUMBER

Build url is : $BUILD_URL

''', compressLog: true, subject: '[$BUILD_STATUS] - $PROJECT_NAME - $BRANCH_NAME - BUILD# - $BUILD_NUMBER', to: 'testautomationwizard@gmail.com' 
      }
      
  } 
}