pipeline {
  agent any
  //Parameterize the build
  parameters {
  	choice (name :'VERSION',choices:['1.1.0','1.2.0','1.3.0'], description:'The version of automation code')
    booleanParam(name: 'RunPreCleanup', defaultValue: true, description: 'To cleanup the Jenkins workspace') 
  }
  
  stages {
    stage("Cleanup Workspace") {
     when{
          expression {
             params.RunPreCleanup
          }     
      }  
      steps {
        deleteDir()
      }
    }
    stage("Checkout TestAutomation Project") {
      steps {
      	echo 'deploying the version: ${params.VERSION}'
        git branch: 'master',
        url: 'https://github.com/prateeksethiDev/Test_UI_API_Repo.git',
        credentialsId: 'GitDevAccount'
      }
    }
    stage("Spin up the Selenium Grid") {
      steps {
      	echo 'Spining up the Selenium Grid'
         sh label: '',script: 'docker-compose -f ./docker-compose-v3.yml up --scale chrome=3'
      }
    }
    stage("Build and run tests") {
      steps {
        echo 'Running Test Automation'
    	sh label: '', script: 'mvn -f MobileAutomata/pom.xml clean test'
      }
    }  
  }
  //The post step as sending email that executed always 
  post{    
      always{
             emailext attachLog: true, body: '''Hello Admin,

Please find the the attached test execution report for project: $PROJECT_NAME - BUILD# - $BUILD_NUMBER

Build url is : $BUILD_URL

''', compressLog: true, subject: '[$BUILD_STATUS] - $PROJECT_NAME - $BRANCH_NAME - BUILD# - $BUILD_NUMBER', to: 'testautomationwizard@gmail.com' 
      }
      always{
            sh label: '',script: 'docker-compose -f ./docker-compose-v3.yml down'
      }
  } 
}